server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: sK0d4X33!
    key-store-type: PKCS12
    key-alias: mycert
  servlet:
    encoding:
      charset: UTF-8
      force: true

spoonacularResults: 5
SpoonacularApiKey: YOUR_KEY_HERE

---

spring:
  config:
    activate:
      on-profile: jdbc
  application:
    name: "Coding Example JDBC"
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5000/app_example
    username: app_user
    password: MyP455W0rd
    statement-cache-size: 250
    statement-cache-sql-limit: 2048
    hikari:
      pool-name: MyHikariPool
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000


---

spring:
  config:
    activate:
      on-profile: jpa
  application:
    name: "Coding Example ORM"
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5000/app_example
    username: app_user
    password: MyP455W0rd
    statement-cache-size: 250
    statement-cache-sql-limit: 2048
  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: h2
  application:
    name: "Coding Example JDBC-H2"
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:app_example
    username: sa
    password:
    statement-cache-size: 250
    statement-cache-sql-limit: 2048
  liquibase:
    enabled: true
    changelog: classpath:db/changelog/db.changelog-h2.yaml
    url: jdbc:h2:mem:app_example;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS app_example
    user: sa
    password:
    default-schema: app_example
    drop-first: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none



